image: node:12.17.0

stages:
  - development
  - release

cache:
  paths:
    - node_modules/

before_script:
  - /bin/bash -c "$(curl -fsSL https://git.heyooo.com/snippets/2/raw)" $NPM_HOST $USERNAME $PASSWORD
  - npm config set always-auth true
  - yarn install

development:
  stage: development
  only:
    - master
  cache:
    paths:
      - node_modules/
  script: |
    echo "=> Building"
    echo "${QINIU_CONFIG}" > dashboard/.qiniurc
    yarn install
    yarn workspace @heyforms/vite-plugin-html-injection build
    yarn workspace @heyforms/vite-plugin-upload build
    yarn workspace heyform staging

    echo "=> Packing"
    mkdir -p tmp/view/
    mkdir -p tmp/static/
    cp dashboard/dist/*.html tmp/view/
    cp dashboard/dist/sw.js tmp/static/sw.js
    cp -r dashboard/dist/static/* tmp/static/

    if [ -f d.tar.gz ]; then
      rm d.tar.gz
    fi
    tar -czvf d.tar.gz tmp/*

    echo "=> Deploying"
    scp -P "$DEVELOP_PORT" -o stricthostkeychecking=no -C d.tar.gz "$DEVELOP_DEPLOY_USER"@"$DEVELOP_DEPLOY_HOST":"$DEVELOP_TEMP"
    DEPLOY_SHELL="tar -xzf ${DEVELOP_TEMP}/d.tar.gz -C ${DEVELOP_APP_DIR} && rm -rf ${DEVELOP_TEMP}/d.tar.gz && cd ${DEVELOP_APP_DIR} && /usr/bin/cp -r tmp/* ./ && npm start"
    ssh -p "$DEVELOP_PORT" "$DEVELOP_DEPLOY_USER"@"$DEVELOP_DEPLOY_HOST" -t "$DEPLOY_SHELL"
    exit

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^Release_v.*$/'
  cache:
    paths:
      - node_modules/
  script: |
    echo "=> Building"
    echo "${QINIU_CONFIG}" > dashboard/.qiniurc
    yarn install
    yarn workspace @heyforms/vite-plugin-html-injection build
    yarn workspace @heyforms/vite-plugin-upload build
    yarn workspace heyform build

    echo "=> Packing"
    mkdir -p tmp/view/
    mkdir -p tmp/static/
    cp dashboard/dist/*.html tmp/view/
    cp dashboard/dist/sw.js tmp/static/sw.js
    cp -r dashboard/dist/static/* tmp/static/

    if [ -f fe.tar.gz ]; then
      rm fe.tar.gz
    fi
    tar -czvf fe.tar.gz tmp/*

    echo "=> Deploying"
    scp -P "$PRO_DEPLOY_PORT" -o stricthostkeychecking=no -C fe.tar.gz "$PRO_DEPLOY_USER"@"$PRO_DEPLOY_HOST":"$PRO_TEMP"
    DEPLOY_SHELL="tar -xzf ${PRO_TEMP}/fe.tar.gz -C ${PRO_APP_DIR} && cd ${PRO_APP_DIR} && cp -r tmp/* ./ && npm start"
    ssh -p "$PRO_DEPLOY_PORT" "$PRO_DEPLOY_USER"@"$PRO_DEPLOY_HOST" -t "$DEPLOY_SHELL"
    exit
