image: node:12.17.0

stages:
  - development

cache:
  paths:
    - node_modules/

before_script:
  - /bin/bash -c "$(curl -fsSL https://git.heyooo.com/snippets/2/raw)" $NPM_HOST $USERNAME $PASSWORD
  - npm config set always-auth true
  - yarn install

development:
  stage: development
  only:
    - master
  except:
    changes:
      - ".gitlab-ci.yml"
  cache:
    paths:
      - node_modules/
  before_script:
    - eval $(ssh-agent -s)
    - echo "$DEVELOP_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  script: |
    echo "=> Building"
    echo "${QINIU_CONFIG}" > dashboard/.qiniurc
    yarn install
    yarn workspace @heyforms/vite-plugin-font-optimization build
    yarn workspace @heyforms/vite-plugin-upload build
    yarn workspace @heyforms/ui build
    yarn workspace heyform staging

    echo "=> Packing"
    mkdir -p tmp/view/
    mkdir -p tmp/static/
    cp dashboard/dist/*.html tmp/view/
    cp dashboard/dist/sw.js tmp/static/sw.js
    cp -r dashboard/dist/static/* tmp/static/

    if [ -f d.tar.gz ]; then
      rm d.tar.gz
    fi
    tar -czvf d.tar.gz tmp/*

    echo "=> Deploying"
    scp -o stricthostkeychecking=no -C d.tar.gz "$DEVELOP_DEPLOY_USER"@"$DEVELOP_DEPLOY_HOST":"$DEVELOP_TEMP"
    DEPLOY_SHELL="tar -xzf ${DEVELOP_TEMP}/d.tar.gz -C ${DEVELOP_APP_DIR} && rm -rf ${DEVELOP_TEMP}/d.tar.gz && cd ${DEVELOP_APP_DIR} && /usr/bin/cp -r tmp/* ./ && npm start"
    ssh -t "$DEVELOP_DEPLOY_USER"@"$DEVELOP_DEPLOY_HOST" "$DEPLOY_SHELL"
    exit
